# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d98cde2f5afec2a343653046393b309b67f7ffd410f360b0f30dd56e9c38bb99dde2a6e12ff05567127375a6727943cb17630117091cdd32f6eec26c18813e5d

test:
  secret_key_base: 4c625d98f720a2bec726c0c1dde3303489fbc8aff042c336ff5eb35b228e75670213745fa7d298b89ffdebb918ddc7578dbf6a417d659b2cbd0ebf5d329955a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
